### ISSUE TITLE
This package does not work after the telegraf 1.15.1 update

### ISSUE THREAD

**Issue by jschoewe** [ripclawffb/chocolatey-telegraf#8]
The name of the folder in the new telegraf zip file below is no longer "telegraf" but "telegraf-1.15.1"

https://dl.influxdata.com/telegraf/releases/telegraf-1.15.1_windows_amd64.zip

I'm not sure why the files in this repo are different from the ones on chocolatey's site (https://chocolatey.org/packages/telegraf#files) but changing $install_folder from "$unzip_folder\telegraf" to "$unzip_folder\telegraf-1.15.1" should fix the issue

**Comment by ripclawffb** [comment]
Thanks for the heads up. Ideally we can keep it in the `telegraf` folder to keep it consistent.

**Comment by ripclawffb** [comment]
This should be resolved now. I released a new patch version of this package.
